### ISSUE TITLE
Ability to test mainnet upgrade with mainnet data

### ISSUE THREAD

**Issue by pgoos** [dymensionxyz/e2e-tests#10]
We want to be able to test with mainnet data locally. Ideally using a couple of validators (not one).
We need a simple framework that would let us spin up such environment easily.
Omri worked on related ticket a few months ago. I will share the code he created for that.

**Comment by anhductn2001** [comment]
I think we can close it

**Comment by omritoptix** [comment]
@anhductn2001 can we close it?
