### ISSUE TITLE
Support for running 3rd party chains in e2e

### ISSUE THREAD

**Issue by pgoos** [dymensionxyz/e2e-tests#13]
To support PFM testing, it’s important to add the ability to our current infra to run third party chains to have a full coverage 
* could we build, store and then use the osmosis image (can be just one version for now, i.e. latest release)?
* we should connect hub->osmosis with an additional relayer

**Comment by anhductn2001** [comment]
We can close it, @trinitys7 has almost completed his PFM test, which indicates that everything has been supported.
