### ISSUE TITLE
fix genesis event test 

### ISSUE THREAD

**Issue by trinitys7** [dymensionxyz/e2e-tests#139]
Current rollapp-genesis-event-test is failing due to refactor permissioned addresses, we need to fix it

**Comment by trinitys7** [comment]
Blocked by https://github.com/dymensionxyz/rollapp-evm/pull/223

**Comment by omritoptix** [comment]
we reverted to old permissioned address. is this still an issue?

**Comment by anhductn2001** [comment]
It's good now. We can close this.
