### ISSUE TITLE
hub upgrade: add test for upgrade strategy

### ISSUE THREAD

**Issue by anhductn2001** [dymensionxyz/e2e-tests#146]
- [x] 1. Write e2e-test for upgrade a empty hub
- [ ] 2. Write e2e-test for upgrade a hub with data imported

**Comment by omritoptix** [comment]
I think we agreed that we're not gonna pursue (2) for now and simply run the e2e tests on the testnet/devnet.

**Comment by anhductn2001** [comment]
Yep, so I will close this issue.
