### ISSUE TITLE
Add e2e test for rollapp genesis token registration on hub 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/e2e-tests#18]
Phase 1 of the PRD should be tested.

https://www.notion.so/dymension/ADR-x-IBC-Rollapp-Token-Available-on-the-hub-upon-Channel-Creation-1b0a9212f6554ac2ac820cc66bab97f9

issue: https://github.com/dymensionxyz/dymension/issues/617 
PR: https://github.com/dymensionxyz/dymension/pull/642

Expected hub flow:

- [ ] Creating a rollapp with RA genesis tokens on the hub
- [ ] Creating a channel between  rollapp and hub 
- [ ] Sending a GenesisTxEvent on the hub from a permissioned address and minting the rollapp tokens on the hub
- [ ] Transferring tokens back and forward from hub to rollapp and seeing them as expected (Currently this is blocked by [the rollapp implemenation](https://github.com/dymensionxyz/dymension-rdk/issues/319))

**Comment by anhductn2001** [comment]
Could you grant me access to the Notion file, please?
