### ISSUE TITLE
Add e2e tests for new finalization calculation for rollapp batches

### ISSUE THREAD

**Issue by srene** [dymensionxyz/e2e-tests#19]
Dymension Hub PR https://github.com/dymensionxyz/dymension/pull/602 changes how finalization time is calculated.

In the PR, batches are not added in the finalization queue based on the time finalized, but based on submission time, this way, when the _disputeperiod_ in blocks is changed, there are no issues with the batches pending to be finalized. 

In the PR a new function GetPendingFinalizationQueue() has been added to get all pending batches to be finalized using a reverse iterator from height-disputeperiod to last batch finalized, that is called from FinalizeQueue() in the EndBlock(). 

Therefore, after each block the queue is checked for pending finalization states, and updated accordingly, using the _disputeperiod_ time during that block.

To this end, we need to test the batches are finalized correctly, making sure of the following:
* Batches are finalized accordingly, after _disputeperiod_ in blocks.
* When _disputeperiod_ param is changed , the batches are finalized in the new _disputeperiod_ time.
* There are no batches that keep permanently without being finalized in any case (specially when _disputeperiod_ is changed)

**Comment by pgoos** [comment]
In progress now.
However, this ticket is blocked until https://github.com/dymensionxyz/e2e-tests/issues/26 is done
