### ISSUE TITLE
Implement IBC tests

### ISSUE THREAD

**Issue by anhductn2001** [dymensionxyz/e2e-tests#21]
- [x] 1. Grace Period Compliance (rollapp to hub)
- [x] 2. Grace Period Compliance (hub to rollapp)
- [ ] 3. IBC packet sent gets rejected (rollapp to hub)
- [ ] 4. IBC packet sent gets rejected when sent to wrong address (rollapp to hub)
- [ ] 5. IBC packet sent from gets rejected (hub to rollapp)
- [x] 6. Relayer processing is delayed causing IBC packet sent timing out (rollapp to hub)
- [x] 7. Relayer processing is delayed causing IBC packet sent timing out (hub to rollapp)
- [ ] 8. Insufficient Funds Handling (rollapp to hub)
- [ ] 9. Insufficient Funds Handling (hub to rollapp)
- [ ] 10. Network Disruption and Recovery (rollapp to hub)
- [ ] 11. Network Disruption and Recovery (hub to rollapp)
- [ ] 12. Concurrent Transactions Handling (rollapp to hub)
- [ ] 13. Concurrent Transactions Handling (hub to rollapp)
- [ ] 14. Not enough funds on the relayer to clear IBC packet
- [ ] 15. Censorship in IBC Transactions
- [ ] 16. IBC Transaction Order Manipulation (option 1)
- [ ] 17. IBC Transaction Order Manipulation (option 2)
- [ ] 18. Invalid IBC Packet Propagation
- [ ] 19. IBC Packet Withholding
- [ ] 20. IBC Packet Front-Running
- [ ] 21. Incorrect State Information in IBC Packets
- [ ] 22. False Acknowledgement of Fund Release
- [ ] 23. AckError Leading to Double Spending*

Doc: https://docs.google.com/document/d/1yHSraPQ3Tg9gOcb-3y4dAT-HojR4X9Z6bnge_rgo0cE/edit?usp=sharing

**Comment by anhductn2001** [comment]
Pls convert to new issue and create a PR to close it. Thanks

**Comment by pgoos** [comment]
The remaining test cases are not high priority. Instead, we should add to the list IBC + PFM scenarios attached on the screenshots:
<img width="1196" alt="image" src="https://github.com/dymensionxyz/e2e-tests/assets/4013866/e866a62a-9def-4284-920d-b2b0d1365641">

<img width="1163" alt="image" src="https://github.com/dymensionxyz/e2e-tests/assets/4013866/09c8b9a5-b966-4fd5-81b0-0a5381d1f0dc">
