### ISSUE TITLE
Add e2e test cases for failure to submit batch to SL within pre-determined time

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/e2e-tests#248]

**Comment by danwt** [comment]
I think it would be good to have just one simple test:
Don't submit the update for the slash time param, and then check that a slash event was emitted by the hub
If there is at least this, then I think the e2e integration of the feature was correct and the rest of the protocol is already thoroughly tested in UTs

WDYT

**Comment by danwt** [comment]
ok lets close
