### ISSUE TITLE
[E2E Test] Genesis transfers: happy path

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/e2e-tests#255]
### Test Case Type

New

### DRS

EVM

### Target Milestone

3D

### Epic

genesis-bridge

### Test Case Description

When I create a new rollapp, I will specify genesis accounts in the genesis file
After registering the rollapp and sequencer on the hub, then I can open a relayer Hub->RA
After some short time, the transfers will arrive on the Hub
An event will be emitted https://github.com/dymensionxyz/dymension/blob/6a54cf642d61f894231b1f5a7294ec4abc688154/x/rollapp/types/events.go#L23
The bridge will be open for transfers RA->Hub
If I then do a transfer RA->Hub, the bridge will be open Hub->RA also

### Preconditions

- Hub and rollapp are up and running, and registered sequencer and rollapp on Hub
- Rollapp contains correct genesis data

### Test Steps

1. Create Hub
2. Create RA with genesis accounts in genesis
3. Start relayer connection Hub->RA
4. Await RA event https://github.com/dymensionxyz/dymension-rdk/blob/fd8806da3d31e6dffbc96ccd5c8b0f9caf83c54d/x/hub-genesis/keeper/sequence_numbers.go#L77
5. Do a transfer RA->Hub
6. Transfers are now enabled in both directions
7. Await hub event https://github.com/dymensionxyz/dymension/blob/6a54cf642d61f894231b1f5a7294ec4abc688154/x/rollapp/types/events.go#L23

### Expected Results

After the event, the balances on the Hub should match the specified genesis accounts on the RA.
After the events, normal eibc/non-eibc transfers should be possible.

### Live Test

- [ ] Yes

### Comments

There are three relevant PRs which need to land before this test can be done
https://github.com/dymensionxyz/dymension/pull/933
https://github.com/dymensionxyz/dymension-rdk/pull/449
https://github.com/dymensionxyz/rollapp-evm/pull/279
The tests must be run with the new Hub
New functionality should be tested with the new rollapp evm
Existing functionality (may) be backwards-compat tested with the new hub and the old rollapp evm
Ask Dan at Dymension for any questions
IMPORTANT: you SHOULD read the protocol overview here https://github.com/dymensionxyz/dymension/blob/67a424ea0886dc99a9d890f4308c65347bc9daa0/x/rollapp/transfergenesis/doc.go#L1-L11
Additionally, see here for an example rollapp genesis file https://pastebin.com/ji0PiTKW,
    and this PR diff for an understanding of changes to the rollapp setup steps https://github.com/dymensionxyz/rollapp-evm/pull/279/files#diff-2238c8f2eb7e6ce10c76e9d98719c4d2c2913c70d6a19c40b2487ef5019c6eb7
I have not ticked 'live test', but it would be good. Would require Hub upgrade.

**Comment by anhductn2001** [comment]
It was resolved when fixing the existing tests.
