### ISSUE TITLE
Update e2e framework to use rollapp-evm

### ISSUE THREAD

**Issue by pgoos** [dymensionxyz/e2e-tests#26]
There were breaking changes introduced on the hub lately and a fix was applied on the rollapp-evm binary
As the framework used rollapp, we need to update to use rollapp-evm instead.
Right now, all the tests are broken.

**Comment by pgoos** [comment]
@anhductn2001 can you link your branches that you are working on?

**Comment by hoangdv2429** [comment]
https://github.com/decentrio/rollup-e2e-testing/tree/ducnt/rollapp_evm we need to fix it from here.
