### ISSUE TITLE
Update new feature Genesis Bridge

### ISSUE THREAD

**Issue by anhductn2001** [dymensionxyz/e2e-tests#278]
Relate to: https://github.com/dymensionxyz/dymension/pull/933

**Comment by danwt** [comment]
Hey, I'm just adjusting the descriptions of the e2e test issues slightly to account for some slight changes to the protocol since I wrote them

FYI

**Comment by anhductn2001** [comment]
Thank you @danwt, we will check it carefully!

**Comment by danwt** [comment]
Yeah sorry I should have given you a bit more info

So the changes:
The transfers will be blocked in both directions until the genesis transfers RA->Hub are complete.
After the genesis transfers RA->Hub are complete, normal transfers will be enabled RA->Hub.
After 1 normal transfer RA->Hub, then normal transfers Hub->RA will also become enabled.
