### ISSUE TITLE
Additional IBC PFM scenarios

### ISSUE THREAD

**Issue by pgoos** [dymensionxyz/e2e-tests#44]
![image](https://github.com/dymensionxyz/e2e-tests/assets/4013866/acb462f5-b8cb-4151-a5f9-3a933025c8a1)
![image](https://github.com/dymensionxyz/e2e-tests/assets/4013866/019d1e41-4b4c-4b2b-9a83-7b20cc333c1e)

convert them into separate issues and then link related PRs

**Comment by anhductn2001** [comment]
Hey, Do we have it yet? @hoangdv2429 @ThanhNhann
