### ISSUE TITLE
[E2E Test] Sequencer Rotation Misbehavior Detection

### ISSUE THREAD

**Issue by anhductn2001** [dymensionxyz/e2e-tests#560]
### Test Case Type

New

### DRS

ALL

### Target Milestone

3D

### Epic

fraud detection

### Test Case Description

na

### Preconditions

Hub, sequencer, and full node are running

### Test Steps

Specify a dymint fraud which changes next seq  at height N (<gossip, HeaderNextSequencerHash>)

### Expected Results

Fulll node eventually detects and freezes (unhealthy)

### Live Test

- [ ] Yes

**Comment by danwt** [comment]
The test is revealing a known bug: https://github.com/dymensionxyz/research/issues/450
Well done
