### ISSUE TITLE
Add e2e tests for the Denom Metadata registration flow

### ISSUE THREAD

**Issue by zale144** [dymensionxyz/e2e-tests#58]
The tests should cover the flow from registering a new denim metadata on rollapp-evm, to having a new ERC20 contract deployed by the hook in the `evm/x/erc20` module.

 Another flow that is relevant is the IBC transfer, which will expect an erc20 denom to have been registered. If the erc20 token was not registered, the IBC transfer should be rejected with an error.

**Comment by omritoptix** [comment]
test cases can be derived from here: https://www.notion.so/dymension/Rollapp-Genesis-Tokens-on-Hub-94b678c172eb4cb99bf7f7b6f3110109?pvs=4
