### ISSUE TITLE
Validate `VFC` creation upon rollapp genesis event

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/e2e-tests#71]
Once `vfc` will provide queries (https://github.com/dymensionxyz/ethermint/issues/17),
the e2e tests that include metadata registration, should assert for `vfc` contract creation as well

* rollapp_genesis_event --> event triggers rollapp's denom registration -> `vfc` created

#18

**Comment by omritoptix** [comment]
closing as each issue should reference a test case from the spec
